# dissercando uma variável
a = input('Digite algo ')
print('O tipo primitivo desse valor é:', type(a))
print('Só tem espaços:', a.isspace())
print('É um número ?', a.isnumeric())
print('É alfabético ?', a.isalpha())
print('É alfanumério ?', a.isalnum())
print('Está em maúscula ?', a.isupper())
print('Esta em minúscula ?', a.islower())
print('Está capitalizada ?', a.istitle())